
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUrenregistratieService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUrenregistratieService {


    /**
     * 
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IUrenregistratieService/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "service.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "service.RegisterResponse")
    public Boolean register(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IUrenregistratieService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "service.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "service.LoginResponse")
    public Boolean login(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns service.AppUser
     */
    @WebMethod(operationName = "GetUser", action = "http://tempuri.org/IUrenregistratieService/GetUser")
    @WebResult(name = "GetUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUser", targetNamespace = "http://tempuri.org/", className = "service.GetUser")
    @ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://tempuri.org/", className = "service.GetUserResponse")
    public AppUser getUser(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param user
     * @return
     *     returns service.ArrayOfTask
     */
    @WebMethod(operationName = "GetUserTasks", action = "http://tempuri.org/IUrenregistratieService/GetUserTasks")
    @WebResult(name = "GetUserTasksResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetUserTasks", targetNamespace = "http://tempuri.org/", className = "service.GetUserTasks")
    @ResponseWrapper(localName = "GetUserTasksResponse", targetNamespace = "http://tempuri.org/", className = "service.GetUserTasksResponse")
    public ArrayOfTask getUserTasks(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        AppUser user);

    /**
     * 
     * @param hours
     * @param task
     * @param u
     * @return
     *     returns service.AppUser
     */
    @WebMethod(operationName = "SaveHours", action = "http://tempuri.org/IUrenregistratieService/SaveHours")
    @WebResult(name = "SaveHoursResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SaveHours", targetNamespace = "http://tempuri.org/", className = "service.SaveHours")
    @ResponseWrapper(localName = "SaveHoursResponse", targetNamespace = "http://tempuri.org/", className = "service.SaveHoursResponse")
    public AppUser saveHours(
        @WebParam(name = "task", targetNamespace = "http://tempuri.org/")
        String task,
        @WebParam(name = "hours", targetNamespace = "http://tempuri.org/")
        Integer hours,
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        AppUser u);

    /**
     * 
     * @param hours
     * @param task
     * @param u
     * @return
     *     returns service.AppUser
     */
    @WebMethod(operationName = "EditHours", action = "http://tempuri.org/IUrenregistratieService/EditHours")
    @WebResult(name = "EditHoursResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EditHours", targetNamespace = "http://tempuri.org/", className = "service.EditHours")
    @ResponseWrapper(localName = "EditHoursResponse", targetNamespace = "http://tempuri.org/", className = "service.EditHoursResponse")
    public AppUser editHours(
        @WebParam(name = "task", targetNamespace = "http://tempuri.org/")
        String task,
        @WebParam(name = "hours", targetNamespace = "http://tempuri.org/")
        Integer hours,
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        AppUser u);

    /**
     * 
     * @param task
     * @param u
     * @return
     *     returns service.AppUser
     */
    @WebMethod(operationName = "DeleteHours", action = "http://tempuri.org/IUrenregistratieService/DeleteHours")
    @WebResult(name = "DeleteHoursResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteHours", targetNamespace = "http://tempuri.org/", className = "service.DeleteHours")
    @ResponseWrapper(localName = "DeleteHoursResponse", targetNamespace = "http://tempuri.org/", className = "service.DeleteHoursResponse")
    public AppUser deleteHours(
        @WebParam(name = "task", targetNamespace = "http://tempuri.org/")
        String task,
        @WebParam(name = "u", targetNamespace = "http://tempuri.org/")
        AppUser u);

}
